### ISSUE TITLE
Adding Docker support

### ISSUE THREAD

**Issue by uduse** [Park-Hyung-Joo/laygo2_sky130_docs#1]
Hi, are you interested in having Docker support to speed up the setup time for Laygo2? I can draft a Dockerfile in this repository.

**Comment by Park-Hyung-Joo** [comment]
It would be great if you make a Docker image for laygo2 & sky130. Actually, professor Jaeduk-Han developer of Laygo2 has an interest in this job. Because most Korean uses Windows and setting up this system in WSL takes a lot of effort and is often messed up. If your Docker contains magic, netgen, xschem, ngspice, ngspice-lib, PySpice, etc, it could be very useful for Laygo in Windows.

**Comment by uduse** [comment]
Cool, I will do that and submit a PR later.

**Comment by Park-Hyung-Joo** [comment]
Thanks a lot. https://github.com/niftylab/laygo2_workspace_sky130 this is my main repo for Laygo2 workspace

**Comment by uduse** [comment]
I almost finished building the Dockerfile (all toolchains, sky130, and partially Laygo2). However, there are some steps that I couldn't fully bake into my Dockerfile due to some bugs in Laygo2's source code (see [here](https://github.com/niftylab/laygo2/issues/18)). If you are interested in helping me to sort out these issues, we can hope on a quick call to get those sorted out. Alternativelly you can address the problems in the Laygo2 repository and I can test it afterwards.

**Comment by Park-Hyung-Joo** [comment]
I'm neither familiar with myparser nor version management. And it seems Dr.Jaeduk solved this anyway.

**Comment by uduse** [comment]
Closing in favor of https://github.com/niftylab/laygo2_workspace_sky130/pull/8
